-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 17, 2025 at 07:22 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `yashika`
--

-- --------------------------------------------------------

--
-- Table structure for table `cat`
--

CREATE TABLE `cat` (
  `id` int(255) NOT NULL,
  `slug` varchar(1500) NOT NULL,
  `category` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `cat`
--

INSERT INTO `cat` (`id`, `slug`, `category`) VALUES
(54, 'clothes', 'Clothes'),
(55, 'furniture', 'Furniture'),
(56, 'electronics', 'Electronics'),
(59, 'headphones', 'Headphones'),
(60, 'hygine', 'hygine');

-- --------------------------------------------------------

--
-- Table structure for table `cat_2`
--

CREATE TABLE `cat_2` (
  `id` int(255) NOT NULL,
  `category` varchar(1500) NOT NULL,
  `slug` varchar(1500) NOT NULL,
  `category_2` varchar(1500) NOT NULL,
  `slug_2` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `cat_2`
--

INSERT INTO `cat_2` (`id`, `category`, `slug`, `category_2`, `slug_2`) VALUES
(9, 'Top selling', 'top-selling', 'Fruits', 'fruits'),
(11, 'Top Rated', 'top-rated', 'Vegetable', 'vegetable'),
(12, 'Top Review', 'top-review', 'Dry Fruits', 'dry-fruits'),
(14, '', '', 'Fast Food', 'fast-food'),
(15, '', '', 'Drinks', 'drinks'),
(16, 'Clothes', 'clothes', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE `data` (
  `id` int(255) NOT NULL,
  `name` varchar(1500) NOT NULL,
  `detail` varchar(1500) NOT NULL,
  `price` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `data_2`
--

CREATE TABLE `data_2` (
  `id` int(255) NOT NULL,
  `name` varchar(1500) NOT NULL,
  `slug` varchar(1500) NOT NULL,
  `detail` varchar(1500) NOT NULL,
  `price` int(255) NOT NULL,
  `description` varchar(1500) NOT NULL,
  `images` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `data_2`
--

INSERT INTO `data_2` (`id`, `name`, `slug`, `detail`, `price`, `description`, `images`) VALUES
(107, 'Suit', 'clothes', 'Elevate your style with our premium Slim Fit Suit, crafted from a luxurious wool blend for unparalleled comfort and durability', 500, '<p>Make a lasting impression with our Classic Slim Fit Suit, the epitome of modern elegance and sophistication. Designed with meticulous attention to detail, this suit is crafted from a high-quality wool blend, offering a soft texture and breathable comfort for all-day wear. The tailored slim fit enhances your silhouette, while the notch lapels and two-button closure provide timeless appeal.</p>\r\n<p>Available in versatile colors like Navy Blue, Charcoal Grey, and Black, this suit effortlessly adapts to any formal setting, be it weddings, corporate events, or elegant evening outings. Additional features include functional inner pockets, fully lined breathable satin interior, and precision stitching for durability.</p>\r\n<p>Choose from a wide range of sizes, or opt for our custom tailoring service to ensure the perfect fit. Pair it with a crisp shirt and polished shoes to complete your dashing look. Dry clean only for long-lasting quality.&nbsp;&nbsp;</p>\r\n<ul>\r\n<li>A short description emphasizing key features:\r\n<ul>\r\n<li><strong>Fabric:</strong> High-quality wool blend for a soft feel and durability.</li>\r\n<li><strong>Fit:</strong> Tailored for a modern, slim fit.</li>\r\n<li><strong>Features:</strong> Two-button closure, notch lapels, functional inner pockets.</li>\r\n<li><strong>Occasions:</strong> Perfect for weddings, business meetings, or formal events.</li>\r\n</ul>\r\n</li>\r\n</ul>\r\n<h4><strong>3. Price</strong></h4>\r\n<ul>\r\n<li>500Rs</li>\r\n</ul>\r\n<h4><strong>4. Color Options</str', 'f2279ba2d15f5de99c3537d7e76b70c9.png'),
(108, 'Sofa', 'furniture', 'Transform your living space with our modern and luxurious Sofa, crafted with high-density foam cushions for unmatched comfort and upholstered in premium fabric. Featuring a sturdy hardwood frame, sleek design, and versatile color options, this sofa is perfect for any home decor style.', 40000, '<p>Redefine comfort and style with our premium Sofa, designed to be the centerpiece of your living space. This sofa is meticulously crafted with a durable hardwood frame for long-lasting support and upholstered in high-quality fabric that is both soft and resistant to wear.</p>\r\n<p>&nbsp;</p>\r\n<p>The cushions are filled with high-density foam, providing exceptional comfort and shape retention over time. The sleek, contemporary design features clean lines, plush armrests, and perfectly proportioned dimensions, making it a versatile addition to any home.</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;Available in a range of sophisticated color options, such as Charcoal Grey, Classic Beige, and Midnight Blue, this sofa effortlessly complements modern, minimalist, or traditional decor styles.</p>\r\n<ul>\r\n<li><strong>Frame Material:</strong> Solid hardwood frame for durability.</li>\r\n<li><strong>Cushions:</strong> High-density foam for comfort and longevity.</li>\r\n<li><strong>Upholstery:</strong> Premium fabric, resistant to stains and fading.</li>\r\n<li><strong>Dimensions:</strong> 84\" L x 36\" W x 34\" H (custom sizes available).</li>\r\n<li><strong>Seating Capacity:</strong> 3-4 persons.</li>\r\n<li><strong>Care Instructions:</strong> Spot clean with a damp cloth; professional cleaning recommended for deep stains.</li>\r\n</ul>\r\n<p>Perfect for family lounging, entertaining guests, or relaxing after a long day, this sofa combines functionality, comfort, and aesthetic appeal. Add it to your living room for ', 'images.jfif'),
(109, 'Samsung Galaxy', 'electronics', 'Experience cutting-edge technology with our latest smartphone, featuring a sleek design, 6.7-inch AMOLED display, 108MP triple-camera system, and a powerful 5000mAh battery. Equipped with a lightning-fast processor and 5G connectivity, it ensures seamless performance for work and play.', 150000, '<p>OLED edge-to-edge display, delivering vibrant colors and exceptional clarity for streaming, gaming, and browsing.</p>\r\n<p>Capture every moment in breathtaking detail with the advanced 108MP triple-camera system, equipped with ultra-wide, telephoto, and night mode capabilities. The 32MP front-facing camera ensures your selfies and video calls look sharp and professional.</p>\r\n<p>Powered by a state-of-the-art processor and 5G connectivity, this phone provides blazing-fast speeds and smooth multitasking for all your apps and entertainment. The 5000mAh battery with fast-charging support keeps you connected all day long, while the fingerprint sensor and facial recognition offer advanced security.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Display:</strong> 6.7-inch AMOLED, 120Hz refresh rate.</li>\r\n<li><strong>Camera System:</strong> 108MP + 12MP (ultra-wide) + 10MP (telephoto); 32MP front camera.</li>\r\n<li><strong>Processor:</strong> Octa-core 3.2GHz with AI optimization.</li>\r\n<li><strong>Battery:</strong> 5000mAh, 45W fast charging, wireless charging support.</li>\r\n<li><strong>Storage Options:</strong> 128GB, 256GB, 512GB (expandable via microSD).</li>\r\n<li><strong>Operating System:</strong> Android 13 or iOS 17.</li>\r\n<li><strong>Connectivity:</strong> 5G, Wi-Fi 6, Bluetooth 5.3, USB-C.</li>\r\n<li><strong>Build:</strong> Sleek aluminum frame, Gorilla Glass protection.</li>\r\n</ul>\r\n<p>Available in stylish color options like Midnight Black, Cloud White, and Ocean Blue, this ', 'images (1).jfif'),
(110, 'Wireless Headphones', 'headphones', 'Immerse yourself in crystal-clear audio with our premium wireless headphones, featuring active noise cancellation, 40-hour battery life, and Bluetooth 5.3 connectivity. Designed for comfort and durability, they’re perfect for music, calls, and gaming.', 10000, '<p>Rediscover the joy of exceptional sound with our premium wireless headphones, designed for audiophiles and casual listeners alike. Engineered for superior performance, these headphones feature advanced active noise cancellation (ANC) technology, allowing you to block out distractions and focus on your music, calls, or games.</p>\r\n<p>The 40mm dynamic drivers deliver deep bass, crisp mids, and clear highs, ensuring a rich and immersive audio experience. With Bluetooth 5.3 connectivity, you can enjoy seamless pairing, stable connections, and extended range.</p>\r\n<p>Designed for all-day comfort, the headphones boast plush memory foam ear cushions and an adjustable headband to fit every user perfectly. The durable, foldable design makes them easy to carry, while the 40-hour battery life ensures uninterrupted listening. When you&rsquo;re short on time, a quick 10-minute charge gives you up to 4 hours of playtime.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Audio:</strong> 40mm dynamic drivers for high-definition sound.</li>\r\n<li><strong>Noise Cancellation:</strong> Advanced ANC for immersive listening.</li>\r\n<li><strong>Battery Life:</strong> Up to 40 hours of playtime; fast charging supported.</li>\r\n<li><strong>Connectivity:</strong> Bluetooth 5.3, with support for AAC and SBC codecs.</li>\r\n<li><strong>Microphone:</strong> Built-in mic for clear calls and voice assistant access.</li>\r\n<li><strong>Design:</strong> Foldable, lightweight, and adjustable for all-day wear.</li>\r\n<l', 'images (2).jfif'),
(111, 'Compact Two Door Fridge', 'electronics', 'Upgrade your space with our compact two-door fridge, offering a 120-liter capacity, energy-efficient cooling, and a sleek design. Equipped with separate freezer and refrigerator compartments, it’s perfect for small kitchens, dorms, or offices.', 70000, '<p>Introducing the ideal solution for compact spaces, our two-door refrigerator combines functionality, style, and efficiency in a sleek design. With a 120-liter capacity, this fridge is perfect for small kitchens, dorm rooms, offices, or studio apartments.</p>\r\n<p>The separate freezer and refrigerator compartments allow you to organize your food conveniently while keeping your frozen items perfectly preserved. Featuring advanced cooling technology, the fridge maintains optimal temperatures to keep your groceries fresh longer.</p>\r\n<p>Designed with energy efficiency in mind, it consumes minimal power, helping you save on electricity bills. The adjustable shelves and door bins offer customizable storage, while the quiet operation ensures minimal noise, making it perfect for any environment.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Capacity:</strong> 120 liters (90L refrigerator, 30L freezer).</li>\r\n<li><strong>Energy Efficiency:</strong> Rated for low power consumption.</li>\r\n<li><strong>Cooling Technology:</strong> Advanced compressor cooling for consistent temperature.</li>\r\n<li><strong>Design:</strong> Sleek two-door design with a durable finish.</li>\r\n<li><strong>Storage:</strong> Adjustable shelves, door bins, and a vegetable crisper.</li>\r\n<li><strong>Noise Level:</strong> Quiet operation suitable for any room.</li>\r\n<li><strong>Dimensions:</strong> 48 cm (W) x 85 cm (H) x 55 cm (D).</li>\r\n<li><strong>Colors Available:</strong> Stainless Steel, Glossy White, Matte Bl', '65979c2cb910f53d2e6e34ae-3-5cu-ft-compact-refrigerator-mini.jpg'),
(112, 'Samsung Galaxy', 'electronics', 'Experience cutting-edge technology with our latest smartphone, featuring a sleek design, 6.7-inch AMOLED display, 108MP triple-camera system, and a powerful 5000mAh battery. Equipped with a lightning-fast processor and 5G connectivity, it ensures seamless performance for work and play.', 150000, '<p>OLED edge-to-edge display, delivering vibrant colors and exceptional clarity for streaming, gaming, and browsing.</p>\r\n<p>Capture every moment in breathtaking detail with the advanced 108MP triple-camera system, equipped with ultra-wide, telephoto, and night mode capabilities. The 32MP front-facing camera ensures your selfies and video calls look sharp and professional.</p>\r\n<p>Powered by a state-of-the-art processor and 5G connectivity, this phone provides blazing-fast speeds and smooth multitasking for all your apps and entertainment. The 5000mAh battery with fast-charging support keeps you connected all day long, while the fingerprint sensor and facial recognition offer advanced security.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Display:</strong> 6.7-inch AMOLED, 120Hz refresh rate.</li>\r\n<li><strong>Camera System:</strong> 108MP + 12MP (ultra-wide) + 10MP (telephoto); 32MP front camera.</li>\r\n<li><strong>Processor:</strong> Octa-core 3.2GHz with AI optimization.</li>\r\n<li><strong>Battery:</strong> 5000mAh, 45W fast charging, wireless charging support.</li>\r\n<li><strong>Storage Options:</strong> 128GB, 256GB, 512GB (expandable via microSD).</li>\r\n<li><strong>Operating System:</strong> Android 13 or iOS 17.</li>\r\n<li><strong>Connectivity:</strong> 5G, Wi-Fi 6, Bluetooth 5.3, USB-C.</li>\r\n<li><strong>Build:</strong> Sleek aluminum frame, Gorilla Glass protection.</li>\r\n</ul>\r\n<p>Available in stylish color options like Midnight Black, Cloud White, and Ocean Blue, this ', 'images (1).jfif'),
(113, 'Microwave Oven', 'electronics', '&quot;Compact and powerful, this microwave oven provides fast cooking with ease. Perfect for reheating, defrosting, and cooking your favorite meals in minutes. With a user-friendly interface and multiple preset cooking options, it’s the perfect kitchen companion.&quot;', 50000, '<p>reheating leftovers, defrosting frozen items, or preparing full meals, this microwave delivers consistently great results.</p>\r\n<p>It comes equipped with multiple preset cooking functions, including options for popcorn, baked potatoes, pizza, and more, so you can simply press a button and let the microwave do the work. The sleek, modern design fits seamlessly into any kitchen decor, and the easy-to-use control panel makes it accessible for all users. Additionally, the microwave is designed to be energy-efficient, saving both time and electricity.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Power</strong>: 800-1200 watts (depending on model)</li>\r\n<li><strong>Capacity</strong>: 20-30 Liters, perfect for small to medium-sized families</li>\r\n<li><strong>Preset Functions</strong>: Popcorn, reheat, defrost, and more</li>\r\n<li><strong>Auto-Cook Options</strong>: Pre-programmed settings for convenience</li>\r\n<li><strong>Turntable</strong>: Ensures even cooking for all your dishes</li>\r\n<li><strong>Energy Efficient</strong>: Saves electricity while delivering fast results</li>\r\n<li><strong>Interior Material</strong>: Easy-to-clean enamel or stainless steel for added durability</li>\r\n<li><strong>Control Panel</strong>: Simple and intuitive for easy operation</li>\r\n</ul>\r\n<p>Whether you&rsquo;re in need of a quick snack or preparing a full meal, this microwave has everything you need for fast, convenient, and delicious cooking.\"</p>\r\n<p>&nbsp;</p>', 'widget-.webp'),
(114, 'Suit', 'clothes', 'Elevate your style with our premium Slim Fit Suit, crafted from a luxurious wool blend for unparalleled comfort and durability', 500, '<p>Make a lasting impression with our Classic Slim Fit Suit, the epitome of modern elegance and sophistication. Designed with meticulous attention to detail, this suit is crafted from a high-quality wool blend, offering a soft texture and breathable comfort for all-day wear. The tailored slim fit enhances your silhouette, while the notch lapels and two-button closure provide timeless appeal.</p>\r\n<p>Available in versatile colors like Navy Blue, Charcoal Grey, and Black, this suit effortlessly adapts to any formal setting, be it weddings, corporate events, or elegant evening outings. Additional features include functional inner pockets, fully lined breathable satin interior, and precision stitching for durability.</p>\r\n<p>Choose from a wide range of sizes, or opt for our custom tailoring service to ensure the perfect fit. Pair it with a crisp shirt and polished shoes to complete your dashing look. Dry clean only for long-lasting quality.&nbsp;&nbsp;</p>\r\n<ul>\r\n<li>A short description emphasizing key features:\r\n<ul>\r\n<li><strong>Fabric:</strong> High-quality wool blend for a soft feel and durability.</li>\r\n<li><strong>Fit:</strong> Tailored for a modern, slim fit.</li>\r\n<li><strong>Features:</strong> Two-button closure, notch lapels, functional inner pockets.</li>\r\n<li><strong>Occasions:</strong> Perfect for weddings, business meetings, or formal events.</li>\r\n</ul>\r\n</li>\r\n</ul>\r\n<h4><strong>3. Price</strong></h4>\r\n<ul>\r\n<li>500Rs</li>\r\n</ul>\r\n<h4><strong>4. Color Options</str', 'f2279ba2d15f5de99c3537d7e76b70c9.png'),
(115, 'Suit', 'clothes', 'Elevate your style with our premium Slim Fit Suit, crafted from a luxurious wool blend for unparalleled comfort and durability', 500, '<p>Make a lasting impression with our Classic Slim Fit Suit, the epitome of modern elegance and sophistication. Designed with meticulous attention to detail, this suit is crafted from a high-quality wool blend, offering a soft texture and breathable comfort for all-day wear. The tailored slim fit enhances your silhouette, while the notch lapels and two-button closure provide timeless appeal.</p>\r\n<p>Available in versatile colors like Navy Blue, Charcoal Grey, and Black, this suit effortlessly adapts to any formal setting, be it weddings, corporate events, or elegant evening outings. Additional features include functional inner pockets, fully lined breathable satin interior, and precision stitching for durability.</p>\r\n<p>Choose from a wide range of sizes, or opt for our custom tailoring service to ensure the perfect fit. Pair it with a crisp shirt and polished shoes to complete your dashing look. Dry clean only for long-lasting quality.&nbsp;&nbsp;</p>\r\n<ul>\r\n<li>A short description emphasizing key features:\r\n<ul>\r\n<li><strong>Fabric:</strong> High-quality wool blend for a soft feel and durability.</li>\r\n<li><strong>Fit:</strong> Tailored for a modern, slim fit.</li>\r\n<li><strong>Features:</strong> Two-button closure, notch lapels, functional inner pockets.</li>\r\n<li><strong>Occasions:</strong> Perfect for weddings, business meetings, or formal events.</li>\r\n</ul>\r\n</li>\r\n</ul>\r\n<h4><strong>3. Price</strong></h4>\r\n<ul>\r\n<li>500Rs</li>\r\n</ul>\r\n<h4><strong>4. Color Options</str', 'f2279ba2d15f5de99c3537d7e76b70c9.png'),
(116, 'Suit', 'clothes', 'Elevate your style with our premium Slim Fit Suit, crafted from a luxurious wool blend for unparalleled comfort and durability', 500, '<p>Make a lasting impression with our Classic Slim Fit Suit, the epitome of modern elegance and sophistication. Designed with meticulous attention to detail, this suit is crafted from a high-quality wool blend, offering a soft texture and breathable comfort for all-day wear. The tailored slim fit enhances your silhouette, while the notch lapels and two-button closure provide timeless appeal.</p>\r\n<p>Available in versatile colors like Navy Blue, Charcoal Grey, and Black, this suit effortlessly adapts to any formal setting, be it weddings, corporate events, or elegant evening outings. Additional features include functional inner pockets, fully lined breathable satin interior, and precision stitching for durability.</p>\r\n<p>Choose from a wide range of sizes, or opt for our custom tailoring service to ensure the perfect fit. Pair it with a crisp shirt and polished shoes to complete your dashing look. Dry clean only for long-lasting quality.&nbsp;&nbsp;</p>\r\n<ul>\r\n<li>A short description emphasizing key features:\r\n<ul>\r\n<li><strong>Fabric:</strong> High-quality wool blend for a soft feel and durability.</li>\r\n<li><strong>Fit:</strong> Tailored for a modern, slim fit.</li>\r\n<li><strong>Features:</strong> Two-button closure, notch lapels, functional inner pockets.</li>\r\n<li><strong>Occasions:</strong> Perfect for weddings, business meetings, or formal events.</li>\r\n</ul>\r\n</li>\r\n</ul>\r\n<h4><strong>3. Price</strong></h4>\r\n<ul>\r\n<li>500Rs</li>\r\n</ul>\r\n<h4><strong>4. Color Options</str', 'f2279ba2d15f5de99c3537d7e76b70c9.png'),
(117, 'Wireless Headphones', 'headphones', 'Immerse yourself in crystal-clear audio with our premium wireless headphones, featuring active noise cancellation, 40-hour battery life, and Bluetooth 5.3 connectivity. Designed for comfort and durability, they’re perfect for music, calls, and gaming.', 10000, '<p>Rediscover the joy of exceptional sound with our premium wireless headphones, designed for audiophiles and casual listeners alike. Engineered for superior performance, these headphones feature advanced active noise cancellation (ANC) technology, allowing you to block out distractions and focus on your music, calls, or games.</p>\r\n<p>The 40mm dynamic drivers deliver deep bass, crisp mids, and clear highs, ensuring a rich and immersive audio experience. With Bluetooth 5.3 connectivity, you can enjoy seamless pairing, stable connections, and extended range.</p>\r\n<p>Designed for all-day comfort, the headphones boast plush memory foam ear cushions and an adjustable headband to fit every user perfectly. The durable, foldable design makes them easy to carry, while the 40-hour battery life ensures uninterrupted listening. When you&rsquo;re short on time, a quick 10-minute charge gives you up to 4 hours of playtime.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Audio:</strong> 40mm dynamic drivers for high-definition sound.</li>\r\n<li><strong>Noise Cancellation:</strong> Advanced ANC for immersive listening.</li>\r\n<li><strong>Battery Life:</strong> Up to 40 hours of playtime; fast charging supported.</li>\r\n<li><strong>Connectivity:</strong> Bluetooth 5.3, with support for AAC and SBC codecs.</li>\r\n<li><strong>Microphone:</strong> Built-in mic for clear calls and voice assistant access.</li>\r\n<li><strong>Design:</strong> Foldable, lightweight, and adjustable for all-day wear.</li>\r\n<l', 'images (2).jfif'),
(118, 'Wireless Headphones', 'headphones', 'Immerse yourself in crystal-clear audio with our premium wireless headphones, featuring active noise cancellation, 40-hour battery life, and Bluetooth 5.3 connectivity. Designed for comfort and durability, they’re perfect for music, calls, and gaming.', 10000, '<p>Rediscover the joy of exceptional sound with our premium wireless headphones, designed for audiophiles and casual listeners alike. Engineered for superior performance, these headphones feature advanced active noise cancellation (ANC) technology, allowing you to block out distractions and focus on your music, calls, or games.</p>\r\n<p>The 40mm dynamic drivers deliver deep bass, crisp mids, and clear highs, ensuring a rich and immersive audio experience. With Bluetooth 5.3 connectivity, you can enjoy seamless pairing, stable connections, and extended range.</p>\r\n<p>Designed for all-day comfort, the headphones boast plush memory foam ear cushions and an adjustable headband to fit every user perfectly. The durable, foldable design makes them easy to carry, while the 40-hour battery life ensures uninterrupted listening. When you&rsquo;re short on time, a quick 10-minute charge gives you up to 4 hours of playtime.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Audio:</strong> 40mm dynamic drivers for high-definition sound.</li>\r\n<li><strong>Noise Cancellation:</strong> Advanced ANC for immersive listening.</li>\r\n<li><strong>Battery Life:</strong> Up to 40 hours of playtime; fast charging supported.</li>\r\n<li><strong>Connectivity:</strong> Bluetooth 5.3, with support for AAC and SBC codecs.</li>\r\n<li><strong>Microphone:</strong> Built-in mic for clear calls and voice assistant access.</li>\r\n<li><strong>Design:</strong> Foldable, lightweight, and adjustable for all-day wear.</li>\r\n<l', 'images (2).jfif'),
(119, 'Wireless Headphones', 'headphones', 'Immerse yourself in crystal-clear audio with our premium wireless headphones, featuring active noise cancellation, 40-hour battery life, and Bluetooth 5.3 connectivity. Designed for comfort and durability, they’re perfect for music, calls, and gaming.', 10000, '<p>Rediscover the joy of exceptional sound with our premium wireless headphones, designed for audiophiles and casual listeners alike. Engineered for superior performance, these headphones feature advanced active noise cancellation (ANC) technology, allowing you to block out distractions and focus on your music, calls, or games.</p>\r\n<p>The 40mm dynamic drivers deliver deep bass, crisp mids, and clear highs, ensuring a rich and immersive audio experience. With Bluetooth 5.3 connectivity, you can enjoy seamless pairing, stable connections, and extended range.</p>\r\n<p>Designed for all-day comfort, the headphones boast plush memory foam ear cushions and an adjustable headband to fit every user perfectly. The durable, foldable design makes them easy to carry, while the 40-hour battery life ensures uninterrupted listening. When you&rsquo;re short on time, a quick 10-minute charge gives you up to 4 hours of playtime.</p>\r\n<p>Key Features:</p>\r\n<ul>\r\n<li><strong>Audio:</strong> 40mm dynamic drivers for high-definition sound.</li>\r\n<li><strong>Noise Cancellation:</strong> Advanced ANC for immersive listening.</li>\r\n<li><strong>Battery Life:</strong> Up to 40 hours of playtime; fast charging supported.</li>\r\n<li><strong>Connectivity:</strong> Bluetooth 5.3, with support for AAC and SBC codecs.</li>\r\n<li><strong>Microphone:</strong> Built-in mic for clear calls and voice assistant access.</li>\r\n<li><strong>Design:</strong> Foldable, lightweight, and adjustable for all-day wear.</li>\r\n<l', 'images (2).jfif'),
(120, 'Sofa', 'furniture', 'Transform your living space with our modern and luxurious Sofa, crafted with high-density foam cushions for unmatched comfort and upholstered in premium fabric. Featuring a sturdy hardwood frame, sleek design, and versatile color options, this sofa is perfect for any home decor style.', 40000, '<p>Redefine comfort and style with our premium Sofa, designed to be the centerpiece of your living space. This sofa is meticulously crafted with a durable hardwood frame for long-lasting support and upholstered in high-quality fabric that is both soft and resistant to wear.</p>\r\n<p>&nbsp;</p>\r\n<p>The cushions are filled with high-density foam, providing exceptional comfort and shape retention over time. The sleek, contemporary design features clean lines, plush armrests, and perfectly proportioned dimensions, making it a versatile addition to any home.</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;Available in a range of sophisticated color options, such as Charcoal Grey, Classic Beige, and Midnight Blue, this sofa effortlessly complements modern, minimalist, or traditional decor styles.</p>\r\n<ul>\r\n<li><strong>Frame Material:</strong> Solid hardwood frame for durability.</li>\r\n<li><strong>Cushions:</strong> High-density foam for comfort and longevity.</li>\r\n<li><strong>Upholstery:</strong> Premium fabric, resistant to stains and fading.</li>\r\n<li><strong>Dimensions:</strong> 84\" L x 36\" W x 34\" H (custom sizes available).</li>\r\n<li><strong>Seating Capacity:</strong> 3-4 persons.</li>\r\n<li><strong>Care Instructions:</strong> Spot clean with a damp cloth; professional cleaning recommended for deep stains.</li>\r\n</ul>\r\n<p>Perfect for family lounging, entertaining guests, or relaxing after a long day, this sofa combines functionality, comfort, and aesthetic appeal. Add it to your living room for ', 'images.jfif'),
(121, 'Sofa', 'furniture', 'Transform your living space with our modern and luxurious Sofa, crafted with high-density foam cushions for unmatched comfort and upholstered in premium fabric. Featuring a sturdy hardwood frame, sleek design, and versatile color options, this sofa is perfect for any home decor style.', 40000, '<p>Redefine comfort and style with our premium Sofa, designed to be the centerpiece of your living space. This sofa is meticulously crafted with a durable hardwood frame for long-lasting support and upholstered in high-quality fabric that is both soft and resistant to wear.</p>\r\n<p>&nbsp;</p>\r\n<p>The cushions are filled with high-density foam, providing exceptional comfort and shape retention over time. The sleek, contemporary design features clean lines, plush armrests, and perfectly proportioned dimensions, making it a versatile addition to any home.</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;Available in a range of sophisticated color options, such as Charcoal Grey, Classic Beige, and Midnight Blue, this sofa effortlessly complements modern, minimalist, or traditional decor styles.</p>\r\n<ul>\r\n<li><strong>Frame Material:</strong> Solid hardwood frame for durability.</li>\r\n<li><strong>Cushions:</strong> High-density foam for comfort and longevity.</li>\r\n<li><strong>Upholstery:</strong> Premium fabric, resistant to stains and fading.</li>\r\n<li><strong>Dimensions:</strong> 84\" L x 36\" W x 34\" H (custom sizes available).</li>\r\n<li><strong>Seating Capacity:</strong> 3-4 persons.</li>\r\n<li><strong>Care Instructions:</strong> Spot clean with a damp cloth; professional cleaning recommended for deep stains.</li>\r\n</ul>\r\n<p>Perfect for family lounging, entertaining guests, or relaxing after a long day, this sofa combines functionality, comfort, and aesthetic appeal. Add it to your living room for ', 'images.jfif'),
(122, 'Sofa', 'furniture', 'Transform your living space with our modern and luxurious Sofa, crafted with high-density foam cushions for unmatched comfort and upholstered in premium fabric. Featuring a sturdy hardwood frame, sleek design, and versatile color options, this sofa is perfect for any home decor style.', 40000, '<p>Redefine comfort and style with our premium Sofa, designed to be the centerpiece of your living space. This sofa is meticulously crafted with a durable hardwood frame for long-lasting support and upholstered in high-quality fabric that is both soft and resistant to wear.</p>\r\n<p>&nbsp;</p>\r\n<p>The cushions are filled with high-density foam, providing exceptional comfort and shape retention over time. The sleek, contemporary design features clean lines, plush armrests, and perfectly proportioned dimensions, making it a versatile addition to any home.</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;Available in a range of sophisticated color options, such as Charcoal Grey, Classic Beige, and Midnight Blue, this sofa effortlessly complements modern, minimalist, or traditional decor styles.</p>\r\n<ul>\r\n<li><strong>Frame Material:</strong> Solid hardwood frame for durability.</li>\r\n<li><strong>Cushions:</strong> High-density foam for comfort and longevity.</li>\r\n<li><strong>Upholstery:</strong> Premium fabric, resistant to stains and fading.</li>\r\n<li><strong>Dimensions:</strong> 84\" L x 36\" W x 34\" H (custom sizes available).</li>\r\n<li><strong>Seating Capacity:</strong> 3-4 persons.</li>\r\n<li><strong>Care Instructions:</strong> Spot clean with a damp cloth; professional cleaning recommended for deep stains.</li>\r\n</ul>\r\n<p>Perfect for family lounging, entertaining guests, or relaxing after a long day, this sofa combines functionality, comfort, and aesthetic appeal. Add it to your living room for ', 'images.jfif');

-- --------------------------------------------------------

--
-- Table structure for table `data_3`
--

CREATE TABLE `data_3` (
  `id` int(255) NOT NULL,
  `name` varchar(1500) NOT NULL,
  `detail` varchar(1500) NOT NULL,
  `description` varchar(1500) NOT NULL,
  `slug` varchar(1500) NOT NULL,
  `slug_2` varchar(1500) NOT NULL,
  `pic` varchar(1500) NOT NULL,
  `price` int(255) NOT NULL,
  `rating` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `data_3`
--

INSERT INTO `data_3` (`id`, `name`, `detail`, `description`, `slug`, `slug_2`, `pic`, `price`, `rating`) VALUES
(20, 'Apple', 'Apples are nutritious and provide several health benefits:', 'here are thousands of apple varieties, with some of the most popular including:\n\nFuji: Sweet and juicy, great for eating raw.\nGranny Smith: Tart and crisp, ideal for baking.\nGala: Mildly sweet and fragrant, perfect for snacking.\nHoneycrisp: Known for its balance of sweetness and tartness, with an excellent crunch.\nNutritional Benefits\nApples are nutritious and provide several health benefits:\n\nLow in Calories: A medium apple has about 95 calories.\nFiber: Good source of dietary fiber, which aids digestion.\nVitamins: Rich in vitamin C and various antioxidants.\nHeart Health: May help reduce the risk of heart disease due to their high fiber and antioxidant content.\nGrowing Conditions\nClimate: Apples thrive in temperate climates.\nSoil: Well-drained, loamy soil is ideal.\nPollination: Most apple varieties require cross-pollination for optimal fruit production.\nCulinary Uses\nRaw: Eaten fresh, sliced, or in salads.\nBaking: Commonly used in pies, crisps, and cakes.\nSauces and Ciders: Made into applesauce or fermented into hard cider.\nStorage\nStore apples in a cool, dry place', 'top-review', 'fruits', 'istockphoto-1214421019-612x612.jpg', 3000, '5'),
(22, 'Cashew', 'Cashew nuts grow attached to the cashew apple, which is also edible and often used to make juices and jams.', '<h3>Botanical Information</h3>\r\n<ul>\r\n<li><strong>Scientific Name</strong>: Anacardium occidentale</li>\r\n<li><strong>Family</strong>: Anacardiaceae</li>\r\n<li><strong>Origin</strong>: Native to Brazil, cashews are now cultivated in tropical regions around the world, including India, Vietnam, and Nigeria.</li>\r\n</ul>\r\n<h3>Nutritional Benefits</h3>\r\n<p>Cashews are nutritious and provide several health benefits:</p>\r\n<ul>\r\n<li><strong>Healthy Fats</strong>: High in monounsaturated fats, which are beneficial for heart health.</li>\r\n<li><strong>Protein</strong>: A good source of plant-based protein.</li>\r\n<li><strong>Vitamins and Minerals</strong>: Rich in magnesium, phosphorus, copper, and zinc.</li>\r\n<li><strong>Antioxidants</strong>: Contains compounds like carotenoids and phenolic compounds that can help reduce inflammation.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<li><strong>Raw</strong>: Eaten as a snack or added to salads.</li>\r\n<li><strong>Roasted</strong>: Commonly roasted and salted for a savory snack.</li>\r\n<li><strong>Dairy Alternatives</strong>: Used to make cashew milk, cream, and cheese in vegan cooking.</li>\r\n<li><strong>Cooking</strong>: Added to stir-fries, curries, and desserts for texture and flavor.</li>\r\n</ul>\r\n<h3>Growing Conditions</h3>\r\n<ul>\r\n<li><strong>Climate</strong>: Requires a tropical climate with well-defined wet and dry seasons.</li>\r\n<li><strong>Soil</strong>: Prefers well-drained sandy soils.</li>\r\n<li><strong>Harvesting</strong>: The cashew a', 'top-rated', 'dry-fruits', '360_F_278420937_amMUMd0A6H4CjPqzoCMYWHjmGblpXJAx.jpg', 10000, '5'),
(23, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-review', 'vegetable', 'images.jfif', 100, '3'),
(24, 'Almond', 'Almonds are a popular and nutritious tree nut known for their crunchy texture and rich flavor. Here’s a detailed overview:', '<ul>\r\n<li><strong>Healthy Fats</strong>: High in monounsaturated fats, which are heart-healthy.</li>\r\n<li><strong>Protein</strong>: A good source of plant-based protein, providing about 6 grams per ounce.</li>\r\n<li><strong>Vitamins and Minerals</strong>: Rich in vitamin E, magnesium, calcium, and potassium.</li>\r\n<li><strong>Antioxidants</strong>: Contains antioxidants like flavonoids, which help combat oxidative stress.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<ul>\r\n<li><strong>Raw or Roasted</strong>: Eaten as a snack, either raw or roasted and salted.</li>\r\n<li><strong>Almond Milk</strong>: Used as a dairy alternative in beverages and recipes.&nbsp;</li>\r\n<li><strong>Climate</strong>: Almond trees thrive in Mediterranean climates with warm, dry summers and mild, wet winters.</li>\r\n<li><strong>Pollination</strong>: Most almond varieties require cross-pollination from other almond trees to produce nuts.</li>\r\n</ul>\r\n</ul>\r\n<h3>Storage</h3>\r\n<ul>\r\n<ul>\r\n<li>Store almonds in an airtight container in a cool, dry place. They can also be refrigerated or frozen for longer shelf life.</li>\r\n</ul>\r\n</ul>', 'top-selling', 'dry-fruits', 'ho07ndkr-500x500.webp', 4000, '5'),
(26, 'Raisins', 'Raisins are dried grapes that are sweet and chewy, making them a popular snack and ingredient in various dishes. Here’s a detailed overview:', '<p>Raisins can be categorized based on the type of grape used and their drying methods:</p>\r\n<ul>\r\n<li><strong>Golden Raisins</strong>: Made from green grapes and dried using sulfur dioxide, resulting in a lighter color and sweeter flavor.</li>\r\n<li><strong>Black Raisins</strong>: Darker in color, usually made from black or red grapes, and typically have a richer flavor.</li>\r\n<li><strong>Sultanas</strong>: Made from a specific type of grape, they are usually plump and juicy with a sweet taste.</li>\r\n</ul>\r\n<h3>Nutritional Benefits</h3>\r\n<p>Raisins are packed with nutrients:</p>\r\n<ul>\r\n<li><strong>Natural Sugars</strong>: High in natural sugars, providing a quick energy boost.</li>\r\n<li><strong>Fiber</strong>: A good source of dietary fiber, aiding in digestion.</li>\r\n<li><strong>Vitamins and Minerals</strong>: Rich in iron, potassium, and antioxidants like polyphenols, which can promote heart health.</li>\r\n<li><strong>Low in Fat</strong>: Raisins contain minimal fat, making them a healthy snack option.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<li><strong>Snacking</strong>: Eaten alone or mixed with nuts for a trail mix.</li>\r\n<li><strong>Baking</strong>: Commonly added to cookies, bread, and cakes.</li>\r\n<li><strong>Cooking</strong>: Used in savory dishes like rice pilafs and tagines for added sweetness.</li>\r\n<li><strong>Salads</strong>: Tossed into salads for a sweet contrast to savory ingredients.</li>\r\n</ul>\r\n<h3>Storage</h3>\r\n<ul>\r\n<li>Store raisins in an airtight con', 'top-review', 'dry-fruits', 'DF_06-02_2048x.webp', 500, '4'),
(28, 'Litchi', ' often described as having a floral flavor. Litchis are typically in season from late spring to summer and ', 'here are thousands of apple varieties, with some of the most popular including:\r\n\r\nFuji: Sweet and juicy, great for eating raw.\r\nGranny Smith: Tart and crisp, ideal for baking.\r\nGala: Mildly sweet and fragrant, perfect for snacking.\r\nHoneycrisp: Known for its balance of sweetness and tartness, with an excellent crunch.\r\nNutritional Benefits\r\nApples are nutritious and provide several health benefits:\r\n\r\nLow in Calories: A medium apple has about 95 calories.\r\nFiber: Good source of dietary fiber, which aids digestion.\r\nVitamins: Rich in vitamin C and various antioxidants.\r\nHeart Health: May help reduce the risk of heart disease due to their high fiber and antioxidant content.\r\nGrowing Conditions\r\nClimate: Apples thrive in temperate climates.\r\nSoil: Well-drained, loamy soil is ideal.\r\nPollination: Most apple varieties require cross-pollination for optimal fruit production.\r\nCulinary Uses\r\nRaw: Eaten fresh, sliced, or in salads.\r\nBaking: Commonly used in pies, crisps, and cakes.\r\nSauces and Ciders: Made into applesauce or fermented into hard cider.\r\nStorage\r\nStore apples in a cool, dry place', 'fresh-product', 'fruits', '360_F_211908888_nogeeJ77XpXH7MbSgO6DNczsZKrdbaXF.jpg', 500, '5'),
(29, 'Apple', 'Apples are nutritious and provide several health benefits:', 'here are thousands of apple varieties, with some of the most popular including:\r\n\r\nFuji: Sweet and juicy, great for eating raw.\r\nGranny Smith: Tart and crisp, ideal for baking.\r\nGala: Mildly sweet and fragrant, perfect for snacking.\r\nHoneycrisp: Known for its balance of sweetness and tartness, with an excellent crunch.\r\nNutritional Benefits\r\nApples are nutritious and provide several health benefits:\r\n\r\nLow in Calories: A medium apple has about 95 calories.\r\nFiber: Good source of dietary fiber, which aids digestion.\r\nVitamins: Rich in vitamin C and various antioxidants.\r\nHeart Health: May help reduce the risk of heart disease due to their high fiber and antioxidant content.\r\nGrowing Conditions\r\nClimate: Apples thrive in temperate climates.\r\nSoil: Well-drained, loamy soil is ideal.\r\nPollination: Most apple varieties require cross-pollination for optimal fruit production.\r\nCulinary Uses\r\nRaw: Eaten fresh, sliced, or in salads.\r\nBaking: Commonly used in pies, crisps, and cakes.\r\nSauces and Ciders: Made into applesauce or fermented into hard cider.\r\nStorage\r\nStore apples in a cool, dry place', 'top-review', 'fruits', 'istockphoto-1214421019-612x612.jpg', 3000, '5'),
(30, 'Carrot', 'Carrots are nutritious and offer numerous health benefits:', '<p>Carrots come in several varieties, including:</p>\r\n<ul>\r\n<li><strong>Nantes</strong>: Sweet, cylindrical shape; great for eating raw.</li>\r\n<li><strong>Imperator</strong>: Long and tapered; commonly found in supermarkets.</li>\r\n<li><strong>Danvers</strong>: Shorter and wider, with a rich flavor, ideal for cooking.</li>\r\n<li><strong>Purple, Yellow, and White Carrots</strong>: These varieties offer unique flavors and colors.</li>\r\n</ul>\r\n<h3>Nutritional Benefits</h3>\r\n<p>Carrots are nutritious and offer numerous health benefits:</p>\r\n<ul>\r\n<li><strong>Low in Calories</strong>: A medium carrot has about 25 calories.</li>\r\n<li><strong>High in Fiber</strong>: Supports digestive health.</li>\r\n<li><strong>Rich in Vitamins</strong>: Especially high in vitamin A (from beta-carotene), vitamin K, and several B vitamins.</li>\r\n<li><strong>Antioxidants</strong>: Contain antioxidants that may help reduce the risk of chronic diseases.</li>\r\n</ul>\r\n<h3>Growing Conditions</h3>\r\n<ul>\r\n<li><strong>Climate</strong>: Thrive in cool weather, ideally between 60-70&deg;F (15-21&deg;C).</li>\r\n<li><strong>Soil</strong>: Prefer loose, well-drained soil to allow for proper root development.</li>\r\n<li><strong>Sunlight</strong>: Require full sun for optimal growth.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<li><strong>Raw</strong>: Eaten as snacks, in salads, or as sticks with dips.</li>\r\n<li><strong>Cooked</strong>: Commonly used in soups, stews, stir-fries, and roasted dishes.</li>\r\n<li><strong>Juic', 'top-review', 'vegetable', '360_F_80961739_hep1UZaQRsy5WQOYU3jkOr5CB7A6xc3U.jpg', 500, '3'),
(31, 'Cashew', 'Cashew nuts grow attached to the cashew apple, which is also edible and often used to make juices and jams.', '<h3>Botanical Information</h3>\r\n<ul>\r\n<li><strong>Scientific Name</strong>: Anacardium occidentale</li>\r\n<li><strong>Family</strong>: Anacardiaceae</li>\r\n<li><strong>Origin</strong>: Native to Brazil, cashews are now cultivated in tropical regions around the world, including India, Vietnam, and Nigeria.</li>\r\n</ul>\r\n<h3>Nutritional Benefits</h3>\r\n<p>Cashews are nutritious and provide several health benefits:</p>\r\n<ul>\r\n<li><strong>Healthy Fats</strong>: High in monounsaturated fats, which are beneficial for heart health.</li>\r\n<li><strong>Protein</strong>: A good source of plant-based protein.</li>\r\n<li><strong>Vitamins and Minerals</strong>: Rich in magnesium, phosphorus, copper, and zinc.</li>\r\n<li><strong>Antioxidants</strong>: Contains compounds like carotenoids and phenolic compounds that can help reduce inflammation.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<li><strong>Raw</strong>: Eaten as a snack or added to salads.</li>\r\n<li><strong>Roasted</strong>: Commonly roasted and salted for a savory snack.</li>\r\n<li><strong>Dairy Alternatives</strong>: Used to make cashew milk, cream, and cheese in vegan cooking.</li>\r\n<li><strong>Cooking</strong>: Added to stir-fries, curries, and desserts for texture and flavor.</li>\r\n</ul>\r\n<h3>Growing Conditions</h3>\r\n<ul>\r\n<li><strong>Climate</strong>: Requires a tropical climate with well-defined wet and dry seasons.</li>\r\n<li><strong>Soil</strong>: Prefers well-drained sandy soils.</li>\r\n<li><strong>Harvesting</strong>: The cashew a', 'top-rated', 'dry-fruits', '360_F_278420937_amMUMd0A6H4CjPqzoCMYWHjmGblpXJAx.jpg', 10000, '5'),
(32, 'Carrot', 'Carrots are nutritious and offer numerous health benefits:', '<p>Carrots come in several varieties, including:</p>\r\n<ul>\r\n<li><strong>Nantes</strong>: Sweet, cylindrical shape; great for eating raw.</li>\r\n<li><strong>Imperator</strong>: Long and tapered; commonly found in supermarkets.</li>\r\n<li><strong>Danvers</strong>: Shorter and wider, with a rich flavor, ideal for cooking.</li>\r\n<li><strong>Purple, Yellow, and White Carrots</strong>: These varieties offer unique flavors and colors.</li>\r\n</ul>\r\n<h3>Nutritional Benefits</h3>\r\n<p>Carrots are nutritious and offer numerous health benefits:</p>\r\n<ul>\r\n<li><strong>Low in Calories</strong>: A medium carrot has about 25 calories.</li>\r\n<li><strong>High in Fiber</strong>: Supports digestive health.</li>\r\n<li><strong>Rich in Vitamins</strong>: Especially high in vitamin A (from beta-carotene), vitamin K, and several B vitamins.</li>\r\n<li><strong>Antioxidants</strong>: Contain antioxidants that may help reduce the risk of chronic diseases.</li>\r\n</ul>\r\n<h3>Growing Conditions</h3>\r\n<ul>\r\n<li><strong>Climate</strong>: Thrive in cool weather, ideally between 60-70&deg;F (15-21&deg;C).</li>\r\n<li><strong>Soil</strong>: Prefer loose, well-drained soil to allow for proper root development.</li>\r\n<li><strong>Sunlight</strong>: Require full sun for optimal growth.</li>\r\n</ul>\r\n<h3>Culinary Uses</h3>\r\n<ul>\r\n<li><strong>Raw</strong>: Eaten as snacks, in salads, or as sticks with dips.</li>\r\n<li><strong>Cooked</strong>: Commonly used in soups, stews, stir-fries, and roasted dishes.</li>\r\n<li><strong>Juic', 'top-rated', 'vegetable', '360_F_80961739_hep1UZaQRsy5WQOYU3jkOr5CB7A6xc3U.jpg', 500, '3'),
(33, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-review', 'vegetable', 'images.jfif', 100, '3'),
(34, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-rated', 'vegetable', 'images.jfif', 100, '3'),
(35, 'Litchi', ' often described as having a floral flavor. Litchis are typically in season from late spring to summer and ', 'ychee (or litchi) is a tropical fruit known for its sweet, floral flavor and unique texture. Here’s a detailed overview:\r\n\r\nBotanical Information\r\nScientific Name: Litchi chinensis\r\nFamily: Sapindaceae\r\nOrigin: Native to southern China, lychee is also grown in other tropical and subtropical regions, including India, Thailand, and Vietnam.\r\nNutritional Benefits\r\nLychee is not only delicious but also nutritious:\r\n\r\nLow in Calories: Approximately 66 calories per 100 grams.\r\nVitamins and Minerals: Rich in vitamin C, vitamin B6, copper, and potassium.\r\nAntioxidants: Contains polyphenols, which may have anti-inflammatory and anti-cancer properties.\r\nCulinary Uses\r\nFresh Consumption: Eaten raw as a refreshing snack.\r\nDesserts: Used in fruit salads, sorbets, and puddings.\r\nSavory Dishes: Occasionally added to stir-fries or salads for a sweet contrast.\r\nBeverages: Made into juices, smoothies, or cocktails.\r\nGrowing Conditions\r\nClimate: Thrives in warm, humid climates with plenty of rainfall.\r\nSoil: Prefers well-drained, sandy loam soil.\r\nHarvesting: Lychee fruits are usually harvested when they turn bright red or pink, indicating ripeness.', 'top-selling', 'fruits', '360_F_211908888_nogeeJ77XpXH7MbSgO6DNczsZKrdbaXF.jpg', 500, '5'),
(37, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-review', 'vegetable', 'images.jfif', 100, '3'),
(38, 'Apple', 'Apples are nutritious and provide several health benefits:', 'here are thousands of apple varieties, with some of the most popular including:\r\n\r\nFuji: Sweet and juicy, great for eating raw.\r\nGranny Smith: Tart and crisp, ideal for baking.\r\nGala: Mildly sweet and fragrant, perfect for snacking.\r\nHoneycrisp: Known for its balance of sweetness and tartness, with an excellent crunch.\r\nNutritional Benefits\r\nApples are nutritious and provide several health benefits:\r\n\r\nLow in Calories: A medium apple has about 95 calories.\r\nFiber: Good source of dietary fiber, which aids digestion.\r\nVitamins: Rich in vitamin C and various antioxidants.\r\nHeart Health: May help reduce the risk of heart disease due to their high fiber and antioxidant content.\r\nGrowing Conditions\r\nClimate: Apples thrive in temperate climates.\r\nSoil: Well-drained, loamy soil is ideal.\r\nPollination: Most apple varieties require cross-pollination for optimal fruit production.\r\nCulinary Uses\r\nRaw: Eaten fresh, sliced, or in salads.\r\nBaking: Commonly used in pies, crisps, and cakes.\r\nSauces and Ciders: Made into applesauce or fermented into hard cider.\r\nStorage\r\nStore apples in a cool, dry place', 'top-selling', 'fruits', 'istockphoto-1214421019-612x612.jpg', 3000, '5'),
(39, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-selling', 'vegetable', 'images.jfif', 100, '3'),
(40, 'Vegetable', 'Vegetables can be categorized into several groups:', '<p>Vegetables can be categorized into several groups:</p>\r\n<ol>\r\n<li>\r\n<p><strong>Leafy Greens</strong>:</p>\r\n<ul>\r\n<li>Examples: Spinach, kale, lettuce, Swiss chard.</li>\r\n<li>Benefits: High in vitamins A, C, K, and minerals like iron and calcium.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Cruciferous</strong>:</p>\r\n<ul>\r\n<li>Examples: Broccoli, cauliflower, Brussels sprouts, cabbage.</li>\r\n<li>Benefits: Rich in fiber, vitamins C and K, and compounds that may have cancer-fighting properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Root Vegetables</strong>:</p>\r\n<ul>\r\n<li>Examples: Carrots, beets, turnips, radishes.</li>\r\n<li>Benefits: Generally high in fiber and various vitamins, especially beta-carotene.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Alliums</strong>:</p>\r\n<ul>\r\n<li>Examples: Onions, garlic, leeks, shallots.</li>\r\n<li>Benefits: Contain compounds that may boost immune function and have anti-inflammatory properties.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Nightshades</strong>:</p>\r\n<ul>\r\n<li>Examples: Tomatoes, potatoes, eggplants, bell peppers.</li>\r\n<li>Benefits: High in vitamins and antioxidants, particularly lycopene in tomatoes.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p><strong>Legumes</strong>:</p>\r\n<ul>\r\n<li>Examples: Peas, beans, lentils.</li>\r\n<li>Benefits: High in protein, fiber, and essential nutrients like iron and folate.</li>\r\n</ul>\r\n</li>\r\n<li>\r\n<p>&nbsp;</p>\r\n</li>\r\n</ol>', 'top-rated', 'vegetable', 'images.jfif', 100, '3');

-- --------------------------------------------------------

--
-- Table structure for table `payment`
--

CREATE TABLE `payment` (
  `id` int(255) NOT NULL,
  `uname` varchar(1500) NOT NULL,
  `pname` varchar(1500) NOT NULL,
  `pic` varchar(1500) NOT NULL,
  `price` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `payment`
--

INSERT INTO `payment` (`id`, `uname`, `pname`, `pic`, `price`) VALUES
(65, 'jaiswal@gmail.com', 'Apple', 'istockphoto-1214421019-612x612.jpg', 3000),
(66, 'jaiswal@gmail.com', 'Almond', 'ho07ndkr-500x500.webp', 4000);

-- --------------------------------------------------------

--
-- Table structure for table `student`
--

CREATE TABLE `student` (
  `id` int(255) NOT NULL,
  `first` varchar(1500) NOT NULL,
  `last` varchar(1500) NOT NULL,
  `email` varchar(1500) NOT NULL,
  `password` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cat`
--
ALTER TABLE `cat`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `cat_2`
--
ALTER TABLE `cat_2`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `data`
--
ALTER TABLE `data`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `data_2`
--
ALTER TABLE `data_2`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `data_3`
--
ALTER TABLE `data_3`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `payment`
--
ALTER TABLE `payment`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `student`
--
ALTER TABLE `student`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cat`
--
ALTER TABLE `cat`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=61;

--
-- AUTO_INCREMENT for table `cat_2`
--
ALTER TABLE `cat_2`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `data`
--
ALTER TABLE `data`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `data_2`
--
ALTER TABLE `data_2`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=123;

--
-- AUTO_INCREMENT for table `data_3`
--
ALTER TABLE `data_3`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `payment`
--
ALTER TABLE `payment`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=67;

--
-- AUTO_INCREMENT for table `student`
--
ALTER TABLE `student`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
